### ISSUE TITLE
attempt eslint + prettier

### ISSUE THREAD

**Issue by russellgoldenberg** [russellgoldenberg/svelte-starter#5]

**Comment by russellgoldenberg** [comment]
https://github.com/mhkeller/layercake/blob/master/.eslintrc

**Comment by mhkeller** [comment]
Fyi these are the install instructions that I use to get that eslint config to work. It's the airbnb base and then I've just thrown on rules that squelch things I find annoying or might have gone against svelte patterns iirc -- not super scientific but it works...

```
npm install-peerdeps --dev eslint-config-airbnb-base eslint-plugin-svelte3
```
